/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesServerFunctionsRouteImport } from './routes/examples/server-functions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesServerFunctionsRoute = ExamplesServerFunctionsRouteImport.update({
  id: '/examples/server-functions',
  path: '/examples/server-functions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/server-functions': typeof ExamplesServerFunctionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/server-functions': typeof ExamplesServerFunctionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/server-functions': typeof ExamplesServerFunctionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examples/server-functions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples/server-functions'
  id: '__root__' | '/' | '/examples/server-functions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesServerFunctionsRoute: typeof ExamplesServerFunctionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/server-functions': {
      id: '/examples/server-functions'
      path: '/examples/server-functions'
      fullPath: '/examples/server-functions'
      preLoaderRoute: typeof ExamplesServerFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesServerFunctionsRoute: ExamplesServerFunctionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
